add boxctl and bashly scaffolding with bash completion

diff --git a/bashly/goodreads/goodreads b/bashly/goodreads/goodreads
--- a/bashly/goodreads/goodreads
+++ b/bashly/goodreads/goodreads
@@ -26,8 +26,9 @@ goodreads_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   Manage goodreads.com login sessions\n" "auth "
-  printf "  %s   Manage the local cache of scraped goodreads.com blog posts\n" "blogs"
+  printf "  %s   Print a bash completions script\n" "completions"
+  printf "  %s   Manage goodreads.com login sessions\n" "auth       "
+  printf "  %s   Manage the local cache of scraped goodreads.com blog posts\n" "blogs      "
   echo
 
   # :command.long_usage
@@ -51,6 +52,37 @@ goodreads_usage() {
     echo
     printf "  %s\n" "--version, -v"
     printf "    Show version number\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+goodreads_completions_usage() {
+  printf "goodreads completions - Print a bash completions script\n\n"
+
+  printf "%s\n" "Usage:"
+  printf "  goodreads completions [SHELL]\n"
+  printf "  goodreads completions --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "SHELL"
+    printf "    Shell to generate completions for (only bash is currently supported)\n"
+    printf "    %s\n" "Allowed: bash"
+    printf "    %s\n" "Default: bash"
     echo
 
   fi
@@ -1655,7 +1687,121 @@ ini_keys() {
   for a in "${keys[@]}"; do echo "$a"; done | sort
 }
 
+# src/lib/send_completions.sh
+send_completions() {
+  echo $'# goodreads completion                                     -*- shell-script -*-'
+  echo $''
+  echo $'# This bash completions script was generated by'
+  echo $'# completely (https://github.com/dannyben/completely)'
+  echo $'# Modifying it manually is not recommended'
+  echo $''
+  echo $'_goodreads_completions_filter() {'
+  echo $'  local words="$1"'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local result=()'
+  echo $''
+  echo $'  if [[ "${cur:0:1}" == "-" ]]; then'
+  echo $'    echo "$words"'
+  echo $''
+  echo $'  else'
+  echo $'    for word in $words; do'
+  echo $'      [[ "${word:0:1}" != "-" ]] && result+=("$word")'
+  echo $'    done'
+  echo $''
+  echo $'    echo "${result[*]}"'
+  echo $''
+  echo $'  fi'
+  echo $'}'
+  echo $''
+  echo $'_goodreads_completions() {'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")'
+  echo $'  local compline="${compwords[*]}"'
+  echo $''
+  echo $'  case "$compline" in'
+  echo $'    *\'blogs challenge\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goodreads_completions_filter "--auto --help --no --yes -a -h -n -y")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'blogs delete\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goodreads_completions_filter "--all --help -a -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'blogs update\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goodreads_completions_filter "--all --help -a -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'completions\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goodreads_completions_filter "--help -h bash")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'auth import\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goodreads_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'auth status\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goodreads_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'auth switch\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goodreads_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'auth logout\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goodreads_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'blogs list\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goodreads_completions_filter "$(ls "${GOODREADS_DATA:-$HOME/.goodreads}/blogs" 2>/dev/null | sed "s/\.json$//") --all --help --limit --reverse --since --until -a -h -l -r -s -u")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'auth list\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goodreads_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'blogs get\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goodreads_completions_filter "--help --json -J -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'blogs rm\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goodreads_completions_filter "--all --help -a -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'blogs ls\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goodreads_completions_filter "$(ls "${GOODREADS_DATA:-$HOME/.goodreads}/blogs" 2>/dev/null | sed "s/\.json$//") --all --help --limit --reverse --since --until -a -h -l -r -s -u")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'auth ls\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goodreads_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'blogs\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goodreads_completions_filter "--help -h challenge delete get list ls rm update")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'auth\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goodreads_completions_filter "--help -h import list logout ls status switch")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_goodreads_completions_filter "--data-path --help --offline --version -h -v auth blogs completions")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'  esac'
+  echo $'} &&'
+  echo $'  complete -F _goodreads_completions goodreads'
+  echo $''
+  echo $'# ex: filetype=sh'
+}
+
 # :command.command_functions
+# :command.function
+goodreads_completions_command() {
+
+  # src/completions_command.sh
+  send_completions
+
+}
 
 # :command.function
 goodreads_auth_import_command() {
@@ -2382,6 +2528,13 @@ parse_requirements() {
   case $action in
     -*) ;;
 
+    completions)
+      action="completions"
+      shift
+      goodreads_completions_parse_requirements "$@"
+      shift $#
+      ;;
+
     auth)
       action="auth"
       shift
@@ -2429,6 +2582,66 @@ parse_requirements() {
 
     esac
   done
+
+}
+
+# :command.parse_requirements
+goodreads_completions_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        goodreads_completions_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="completions"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        # :argument.case
+        if [[ -z ${args['shell']+x} ]]; then
+          args['shell']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+  # :command.default_assignments
+  [[ -n ${args['shell']:-} ]] || args['shell']="bash"
+
+  # :command.whitelist_filter
+  if [[ -n ${args['shell']:-} ]] && [[ ! ${args['shell']:-} =~ ^(bash)$ ]]; then
+    printf "%s\n" "shell must be one of: bash" >&2
+    exit 1
+  fi
 
 }
 
@@ -3282,6 +3495,7 @@ run() {
   before_hook
 
   case "$action" in
+    "completions") goodreads_completions_command ;;
     "auth") goodreads_auth_command ;;
     "auth import") goodreads_auth_import_command ;;
     "auth status") goodreads_auth_status_command ;;
